# Generated by ModSync. Stored under UltimMC\ModSync\launch-hooks, never in the game folder.
$ErrorActionPreference = 'Stop'
try {
    if (-not $env:INST_MC_DIR -or -not (Test-Path -LiteralPath $env:INST_MC_DIR -PathType Container)) {
        throw 'UltimMC did not supply a valid Minecraft game folder.'
    }
    $previous = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('__PREVIOUS_COMMAND__'))
    if ($previous) {
        # UltimMC substitutes $NAME variables and uses Qt command splitting, not a shell.
        foreach ($item in (Get-ChildItem Env: | Sort-Object Name)) { $previous = $previous.Replace('$' + $item.Name, $item.Value) }
        $parts = New-Object 'System.Collections.Generic.List[string]'
        $part = New-Object Text.StringBuilder
        $quoted = $false
        for ($i = 0; $i -lt $previous.Length; $i++) {
            $c = $previous[$i]
            if ($c -eq '"') {
                if ($i + 2 -lt $previous.Length -and $previous.Substring($i, 3) -eq '"""') { [void]$part.Append('"'); $i += 2 }
                else { $quoted = -not $quoted }
            } elseif ([char]::IsWhiteSpace($c) -and -not $quoted) {
                if ($part.Length -gt 0) { $parts.Add($part.ToString()); [void]$part.Clear() }
            } else { [void]$part.Append($c) }
        }
        if ($part.Length -gt 0) { $parts.Add($part.ToString()) }
        if ($parts.Count -eq 0) { throw 'The existing pre-launch command is empty after variable expansion.' }
        # Quote individual arguments for Windows CreateProcess; never evaluate user text as PowerShell.
        function Quote-Argument([string]$value) {
            $value = [regex]::Replace($value, '(\\*)"', '$1$1\"')
            $value = [regex]::Replace($value, '(\\+)$', '$1$1')
            return '"' + $value + '"'
        }
        $start = New-Object Diagnostics.ProcessStartInfo
        $start.FileName = $parts[0]
        $argsList = @()
        for ($i = 1; $i -lt $parts.Count; $i++) { $argsList += (Quote-Argument $parts[$i]) }
        $start.Arguments = $argsList -join ' '
        $start.WorkingDirectory = (Get-Location).Path
        $start.UseShellExecute = $false
        $start.CreateNoWindow = $true
        $prior = [Diagnostics.Process]::Start($start)
        $prior.WaitForExit()
        if ($prior.ExitCode -ne 0) { throw ('Your existing pre-launch command failed with code ' + $prior.ExitCode) }
        $prior.Dispose()
    }
    $appFolder = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
    $exe = Join-Path $appFolder 'ModSync.exe'
    if (-not (Test-Path -LiteralPath $exe -PathType Leaf)) { throw 'ModSync.exe is missing. Restore it in UltimMC\ModSync or disable the launch check.' }
    $game = [IO.Path]::GetFullPath($env:INST_MC_DIR).TrimEnd('\')
    if ($game.Contains('"')) { throw 'Invalid game folder.' }
    $broker = Start-Process -FilePath $exe -ArgumentList ('--pre-launch "' + $game + '"') -Verb RunAs -WindowStyle Hidden -PassThru
    $broker.WaitForExit()
    exit $broker.ExitCode
} catch {
    Write-Error -Message ('ModSync launch check stopped: ' + $_.Exception.Message) -ErrorAction Continue
    exit 1
}
